### ISSUE TITLE
Parametrize code variables in bot.py to match each Wikipedia's configuration file.

### ISSUE THREAD

**Issue by EneHacheCe** [wikicurricula-uy/wikicurricula-boilerplate#11]
**IMPORTANT: this issue should be completed after [Issue #12](https://github.com/wikicurricula-uy/wikicurricula-boilerplate/issues/12)**

Currently, bot.py works only with the Spanish Wikipedia.

[An older version of the script](https://github.com/wikicurricula-uy/wikicurricula-boilerplate/blob/main/data-gathering/bot.py) worked only with the Italian Wikipedia.

Instead, we need a script that can work with several Wikipedias.

Example:

You run from the terminal
`python3  bot.py es`

A file called config.json will contain the information necesary to inspect each Wikipedia

```
{
"es" : {
 "language":"es",
"talk":"Discusión:",
"featuredArticle"="{{artículo destacado"
...
},
"en":  {
...
},
"it": {
...
}
```

Include the variables necessary to fetch information from the Spanish and Italian Wikipedia, and optionally, for the English Wikipedia.

**Comment by mpa-mxiang** [comment]
Hi I am interest in this issue but I am wondering how I can find the file called `config.json`.

**Comment by EneHacheCe** [comment]
Hello!
There is no such file yet, you'll need to create it.

Nat

**Comment by mpa-mxiang** [comment]
Hi, 

Thank you for the clarification!

Jiachun

**Comment by EneHacheCe** [comment]
Feel free to suggest other implementations if you come up with alternatives.
The key is to be able to pass the language as a parameter, and for it to work with different Wikis.
You can take a look at @Bhbee 's Pull request https://github.com/wikicurricula-uy/wikicurricula-boilerplate/pull/7, she has already sorted out how to count templates in Spanish

**Comment by mpa-mxiang** [comment]
Hi, I feel it is better to ask again after getting confused for a few days...I am wondering if I just need to add a file like `config.json` or if I need to do something else as the basic.
