### ISSUE TITLE
Update README.md for Improved Project Documentation

### ISSUE THREAD

**Issue by racheallove06** [wikicurricula-uy/wikicurricula-boilerplate#22]
The current README.md for the project is a minimalistic boilerplate, and it could benefit from a more detailed and informative structure to attract potential contributors and provide a clear understanding of the project's objectives. 

Proposed Changes:

1. Add project overview with a brief history and context.
2. Include credits and acknowledgments for contributors and inspiration.
3. Outline project goals and objectives.
4. Provide clear instructions on getting started with contributions.
5. Include a section on contribution guidelines.
6. Highlight the project's current status and ongoing tasks.
7. Add a contact section for inquiries and discussions.

Assignee: @racheallove06

**Comment by Emmafman1** [comment]
I'd like to work on this. Do i need to get it assigned to me?

**Comment by racheallove06** [comment]
Hey Emma, I'm  already working on it 😄
