### ISSUE TITLE
Add tick marks to the x axis in the main visualization page

### ISSUE THREAD

**Issue by wikicurricula-uy** [wikicurricula-uy/wikicurricula-boilerplate#28]
Just like the y axis includes tickmarks, the x axis should as well.
![imagen](https://github.com/wikicurricula-uy/wikicurricula-boilerplate/assets/136046263/fdf82cc5-7b7a-4952-b708-1ad276dfd392)

It is important that the tick marks are readapt when you change the subject in the subjects dropdown and the sorting order.

If you want, you may make the tick marks just for one of the metrics (for example, reference number or creation date). Please specify in your pull request if you implemented only one or some of them.

**Comment by lutfiaomarr** [comment]
hy @wikicurricula-uy im an outreachy applicant and i would like to contribute to this issue. please assign me

**Comment by Urmilasc** [comment]
Hello @wikicurricula-uy  , can we  create x-axis for notes metrics also ?
