### ISSUE TITLE
The Navigation bars for the vsiualization pages are not Responsive enough

### ISSUE THREAD

**Issue by MaryannAlonge** [wikicurricula-uy/wikicurricula-boilerplate#38]
I have figured that the nav bars are static when interacted with, which makes them fall short of the basic standards of web behaviour.

I intend to improve them by writing rules that would make them more interactive.

**Comment by wikicurricula-uy** [comment]
Hello, @MaryannAlonge ! I'm closing the issue and PR since we will not be using the "Enties with warnings" and "authors and publications" tabs for now. All these tabs should remain hidden for now.
