### ISSUE TITLE
Remove "How to contribute" section from the README.md

### ISSUE THREAD

**Issue by wikicurricula-uy** [wikicurricula-uy/wikicurricula-boilerplate#68]
Now that we have a CONTRIBUTING.md, this section of the readme became redundant
https://github.com/wikicurricula-uy/wikicurricula-boilerplate#-how-to-contribute-to-this-projectmake-a-pull-request-pr-to-this-github-repository

If any parts of the process are described better here than in the CONTRIBUTING.md file, please improve CONTRIBUTING.md accordingly.

**Comment by GonzaFP** [comment]
I have made a PR that fixed this issue. Thanks
