### ISSUE TITLE
Translate UI: "Sort by" dropdown options

### ISSUE THREAD

**Issue by wikicurricula-uy** [wikicurricula-uy/wikicurricula-boilerplate#70]
* number of images appears both in English and Spanish (let's keep it only in English)
* "referencia" should be "number of references"

**Comment by GonzaFP** [comment]
hey @wikicurricula-uy I noticed that the entire sort by dropdown is in English. Can I translate it to Spanish?

**Comment by EneHacheCe** [comment]
Sorry I made a mistake. We are aiming to have it all in English for now

**Comment by GonzaFP** [comment]
Al right, Should I remove numero de imagenes and keep number of images?

**Comment by EneHacheCe** [comment]
yes :)
Nathalie
*Conocé mi último libro de cuentos: es lo que tengo* <https://isla.uy/elqt>
