### ISSUE TITLE
Translate UI: Article pop up

### ISSUE THREAD

**Issue by wikicurricula-uy** [wikicurricula-uy/wikicurricula-boilerplate#71]
The pop up that appears when you hover over an article dot in the chart still shows the metrics in Spanish. Let's translate this to English. It is ok that the title of the article appears in Italian or Spanish, since it should be the article name as it appears in the analyzed wikipedia

**Comment by GonzaFP** [comment]
@wikicurricula-uy  I have translated it. Here is my PR https://github.com/wikicurricula-uy/wikicurricula-boilerplate/pull/79#issue-1948838267
