### ISSUE TITLE
Translate UI to English: chart legend fo y axis

### ISSUE THREAD

**Issue by wikicurricula-uy** [wikicurricula-uy/wikicurricula-boilerplate#74]
![imagen](https://github.com/wikicurricula-uy/wikicurricula-boilerplate/assets/136046263/1e7e75a2-132f-4cc2-8a99-a9d4c0f58130)

**Comment by Urmilasc** [comment]
Hello  , In this we need to change this "visitas diarias" to english , I am taking it right ?
